SELECT * FROM sqljbc_members.members;
select * from members
	where role = 'developer4';
select * from members
	order by last_name asc;
select * from members
	order by salary desc;
 select * from members
	where first_name like 's%';